# Generated by Django 3.1.3 on 2020-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор репорта')),
                ('reportTime', models.DateTimeField(auto_now_add=True, verbose_name='Дата репорта')),
                ('reportEndTime', models.DateTimeField(null=True, verbose_name='Дата окончания действия репорта')),
                ('symptoms', models.CharField(blank=True, max_length=50, verbose_name='Симптомы')),
                ('status', models.CharField(choices=[('W', 'Ожидание результатов теста'), ('P', 'Результат положительный'), ('N', 'Результат отрицательный')], default='W', max_length=1, verbose_name='Состояние')),
                ('contact', models.BooleanField(choices=[('N', 'Контакта с носителями не наблюдалось'), ('A', 'Был в контакте с заражёнными'), ('P', 'Был в контакте с потенциальными носителями')], default='N', max_length=1, verbose_name='Контакты')),
                ('places', models.TextField(blank=True, verbose_name='Места пребывания')),
            ],
        ),
    ]
