# Generated by Django 3.1.3 on 2020-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCore', '0002_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact',
            field=models.CharField(choices=[('N', 'Контакта с носителями не наблюдалось'), ('A', 'Был в контакте с заражёнными'), ('P', 'Был в контакте с потенциальными носителями')], default='N', max_length=1, verbose_name='Контакты'),
        ),
    ]
