# Generated by Django 3.1.3 on 2020-11-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCore', '0003_auto_20201125_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportEndTime',
            field=models.DateField(null=True, verbose_name='Дата окончания действия репорта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportTime',
            field=models.DateField(auto_now_add=True, verbose_name='Дата репорта'),
        ),
    ]
