# Generated by Django 3.1.3 on 2020-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportCore', '0004_auto_20201126_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='features',
            field=models.TextField(blank=True, verbose_name='Записи в HERE Data Hub'),
        ),
    ]
