# Generated by Django 3.1.3 on 2020-11-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
