# Generated by Django 3.1.3 on 2020-11-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthCore', '0002_auto_20201124_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
