# Generated by Django 3.1.3 on 2020-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthCore', '0003_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_report',
            field=models.CharField(blank=True, max_length=20, verbose_name='Последний репорт'),
        ),
    ]
